=== Ivigaga/sew_extraordinaria/xml/rutas.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns="http://www.uniovi.es">
	<xs:element name="rutas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="ruta" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ruta">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="tipo" />
				<xs:element ref="transporte" />
				<xs:element minOccurs="0" maxOccurs="1" ref="fecha_incio" />
				<xs:element minOccurs="0" maxOccurs="1" ref="hora_inicio" />
				<xs:element ref="duracion" />
				<xs:element ref="agencia" />
				<xs:element ref="descripcion" />
				<xs:element ref="publico" />
				<xs:element ref="inicio" />
				<xs:element ref="direccion" />
				<xs:element ref="coordenadas" />
				<xs:element ref="referencias" />
				<xs:element ref="recomendacion" />
				<xs:element ref="hitos" />
				<xs:element ref="planimetria" />
				<xs:element ref="altimetria" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="tipo" type="xs:string" />
	<xs:element name="transporte" type="xs:string" />
	<xs:element name="fecha_incio" type="xs:date" />
	<xs:element name="hora_inicio" type="xs:time" />
	<xs:element name="duracion">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="unidadesTiempo"  use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="agencia" type="xs:string" />
	<xs:element name="descripcion" type="xs:string" />
	<xs:element name="publico" type="xs:string" />
	<xs:element name="inicio" type="xs:string" />
	<xs:element name="direccion" type="xs:string" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud">
		<xs:simpleType>
			<xs:restriction base="xs:double">
				<xs:minInclusive value="-90"></xs:minInclusive>
				<xs:maxInclusive value="90"></xs:maxInclusive>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="latitud">
		<xs:simpleType>
			<xs:restriction base="xs:double">
				<xs:minInclusive value="-90"></xs:minInclusive>
				<xs:maxInclusive value="90"></xs:maxInclusive>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="altitud">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="0"></xs:minInclusive>
				<xs:maxExclusive value="8849"></xs:maxExclusive>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="recomendacion" type="xs:string" />
	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="5" maxOccurs="unbounded" ref="hito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="descripcion" />
				<xs:element ref="coordenadas" />
				<xs:element ref="distancia" />
				<xs:element ref="imagenes" />
				<xs:element minOccurs="0" maxOccurs="1" ref="videos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
			
		</xs:complexType>
	</xs:element>
	<xs:element name="imagenes">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="imagen" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="imagen" type="xs:string" />
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="planimetria" type="xs:string" />
	<xs:element name="altimetria" type="xs:string" />


	<xs:simpleType name="unidadesTiempo">
		<xs:restriction base="xs:string">
			<xs:enumeration value="horas"/>
			<xs:enumeration value="días"/>
			<xs:enumeration value="semanas"/>
			<xs:enumeration value="hora"/>
			<xs:enumeration value="día"/>
			<xs:enumeration value="semana"/>
			<xs:enumeration value="minutos"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:notation name="png" public="" system="image/png" />
	<xs:notation name="mp4" public="" system="video/mp4" />
</xs:schema>

=== Ivigaga/sew_extraordinaria/xml/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas xmlns="http://www.uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.uniovi.es rutas.xsd">
    <ruta>
        <nombre>La Vega-Acéu</nombre>
        <tipo>Senderismo</tipo>
        <transporte>A pie</transporte>
        <duracion unidades="horas">1.5</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion>Ruta que va desde La Vega a Acéu</descripcion>
        <publico>Apta para todos</publico>
        <inicio>Plaza de Vega</inicio>
        <direccion>Plaza de Casimiro Vega, 44, 33518 La Vega, Asturias</direccion>
        <coordenadas>
            <longitud>-5.5575</longitud>
            <latitud>43.41056</latitud>
            <altitud>292</altitud>
        </coordenadas>
        <referencias>
            <referencia>https://es.wikipedia.org/wiki/Vega_(Sariego)</referencia>
            <referencia>https://paisaje.asturias.me/comarca-de-la-sidra/c/0/i/77670629/pozu-salau-el</referencia>
            <referencia>https://www.lne.es/centro/2008/10/05/carcabada-pueblo-ejemplar-21634972.html</referencia>
        </referencias>
        <recomendacion>8</recomendacion>
        <hitos>
            <hito>
                <nombre>Fuente Pozu Salau</nombre>
                <descripcion>Fuente cuyo nivel del agua sube y baja al ritmo del Mar Cantábrico</descripcion>
                <coordenadas>
                    <longitud>-5.545008</longitud>
                    <latitud>43.410651</latitud>
                    <altitud>278</altitud>
                </coordenadas>
                <distancia unidades="Km">1.1</distancia>
                <imagenes>
                    <imagen>fuente.jpg</imagen>
                </imagenes>
            </hito>

            <hito>
                <nombre>Estatuas de madera</nombre>
                <descripcion>Figuras de personas de madera</descripcion>
                <coordenadas>
                    <longitud>-5.541796</longitud>
                    <latitud>43.411112</latitud>
                    <altitud>269</altitud>
                </coordenadas>
                <distancia unidades="Km">0.3</distancia>
                <imagenes>
                    <imagen>figuras.jpg</imagen>
                </imagenes>
            </hito>

            <hito>
                <nombre>Premio al pueblo ejemplar</nombre>
                <descripcion>Premio al pueblo ejemplar del concejo, dado a Carcabada en el 2008</descripcion>
                <coordenadas>
                    <longitud>-5.539354</longitud>
                    <latitud>43.40946</latitud>
                    <altitud>284</altitud>
                </coordenadas>
                <distancia unidades="Km">0.3</distancia>
                <imagenes>
                    <imagen>premio.jpg</imagen>
                </imagenes>
            </hito>

            <hito>
                <nombre>Iglesia de San Román</nombre>
                <descripcion>Templo católico de estilo románico</descripcion>
                <coordenadas>
                    <longitud>-5.516392</longitud>
                    <latitud>43.408092</latitud>
                    <altitud>304</altitud>
                </coordenadas>
                <distancia unidades="Km">2.6</distancia>
                <imagenes>
                    <imagen>san_roman.jpg</imagen>
                </imagenes>
            </hito>

            <hito>
                <nombre>Acéu</nombre>
                <descripcion>Fin de la ruta</descripcion>
                <coordenadas>
                    <longitud>-5.514832</longitud>
                    <latitud>43.406689</latitud>
                    <altitud>327</altitud>
                </coordenadas>
                <distancia unidades="Km">0.6</distancia>
                <imagenes>
                    <imagen>aceu.jpg</imagen>
                </imagenes>
            </hito>
        </hitos>
        <planimetria>ruta1.kml</planimetria>
        <altimetria>ruta1.svg</altimetria>
    </ruta>

    <ruta>
        <nombre>Cercanías al cielo</nombre>
        <tipo>Senderismo</tipo>
        <transporte>A pie</transporte>
        <duracion unidades="horas">5</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion>Ruta através de los picos de Sariego</descripcion>
        <publico>Personas en buena forma física</publico>
        <inicio>Plaza de Vega</inicio>
        <direccion>Plaza de Casimiro Vega, 44, 33518 La Vega, Asturias</direccion>
        <coordenadas>
            
            <longitud>-5.5575</longitud>
            <latitud>43.41056</latitud>
            <altitud>292</altitud>
        </coordenadas>
        <referencias>
            <referencia>https://es.wikipedia.org/wiki/Vega_(Sariego)</referencia>
            <referencia>https://sariego.vivirasturias.com/poblaciones/c/0/i/61937566/villar</referencia>
            <referencia>https://www.rtpa.es/noticias-asturias:-La-%27Ruta-de-las-Cercanias-del-Cielo%27-ofrece-un-paisaje-poco-habitual-del-centro-de-Asturias_111646997875.html</referencia>
        </referencias>
        <recomendacion>9</recomendacion>
        <hitos>
            <hito>
                <nombre>Villar</nombre>
                <descripcion>Pueblo rural</descripcion>
                <coordenadas>
                    <longitud>-5.569151</longitud>
                    <latitud>43.417015</latitud>
                    <altitud>390</altitud>
                </coordenadas>
                <distancia unidades="Km">2.2</distancia>
                <imagenes>
                    <imagen>villar.png</imagen>
                </imagenes>
            </hito>

            <hito>
                <nombre>Mirador de Perriellos</nombre>
                <descripcion>Vistas preciosas debido a su estratégica ubicación en el centro de Asturias</descripcion>
                <coordenadas>
                    <longitud> -5.5581</longitud>
                    <latitud> 43.425865</latitud>
                    <altitud>591</altitud>
                </coordenadas>
                <distancia unidades="Km">4.34</distancia>
                <imagenes>
                    <imagen>mirador.jpg</imagen>
                </imagenes>
            </hito>

            <hito>
                <nombre>Pico</nombre>
                <descripcion>Vertice Geodésico</descripcion>
                <coordenadas>
                    <longitud>-5.53</longitud>
                    <latitud>43.424683</latitud>
                    <altitud>604</altitud>
                </coordenadas>
                <distancia unidades="Km">2.76</distancia>
                <imagenes>
                    <imagen>pico.jpg</imagen>
                </imagenes>
            </hito>

            <hito>
                <nombre>Área recreativa</nombre>
                <descripcion>Área recreativa de la ruta de las cercanías del cielo</descripcion>
                <coordenadas>
                    <longitud>-5.5226</longitud>
                    <latitud>43.421749</latitud>
                    <altitud>519</altitud>
                </coordenadas>
                <distancia unidades="Km">1.2</distancia>
                <imagenes>
                    <imagen>recreativa.png</imagen>
                </imagenes>
            </hito>

            <hito>
                <nombre>Estatuas de madera</nombre>
                <descripcion>Figuras de personas de madera</descripcion>
                <coordenadas>
                    <longitud>-5.541796</longitud>
                    <latitud>43.411112</latitud>
                    <altitud>269</altitud>
                </coordenadas>
                <distancia unidades="Km">2.9</distancia>
                <imagenes>
                    <imagen>figuras.jpg</imagen>
                </imagenes>
            </hito>

            <hito>
                <nombre>Plaza de Vega</nombre>
                <descripcion>Fin de la ruta</descripcion>
                <coordenadas>
                    <longitud>-5.5575</longitud>
                    <latitud>43.41056</latitud>
                    <altitud>292</altitud>
                </coordenadas>
                <distancia unidades="Km">1.4</distancia>
                <imagenes>
                    <imagen>plaza.jpg</imagen>
                </imagenes>
            </hito>
        </hitos>
        <planimetria>ruta2.kml</planimetria>
        <altimetria>ruta2.svg</altimetria>
    </ruta>

    <ruta>
        <nombre>Cueva de San Pedrín</nombre>
        <tipo>Paisajística</tipo>
        <transporte>A pie</transporte>
        <duracion unidades="horas">1.35</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion>Ruta que pasa por la cueva de San pedrín y la cantera de Sariego</descripcion>
        <publico>Apta para todos</publico>
        <inicio>Aramanti, Camin de la Viona</inicio>
        <direccion>33518 Sariego, Asturias</direccion>
        <coordenadas>
            <longitud>-5.584403414406851</longitud>
            <latitud>43.41131803384679</latitud>
            <altitud>298</altitud>
        </coordenadas>
        <referencias>
            <referencia>https://www.lne.es/centro/2008/10/05/carcabada-pueblo-ejemplar-21634972.html</referencia>
            <referencia>https://sariego.vivirasturias.com/poblaciones/c/0/i/61937632/la-rimada</referencia>
            <referencia>https://es.wikipedia.org/wiki/Aramanti</referencia>
        </referencias>
        <recomendacion>3</recomendacion>
        <hitos>
            <hito>
                <nombre>Cueva de San Pedrín</nombre>
                <descripcion>Cueva donde se celebra la fista de San Pedrín</descripcion>
                <coordenadas>
                    <longitud>-5.591552</longitud>
                    <latitud>43.414923</latitud>
